source 'https://rubygems.org'

gem 'fluent-plugin-concat', '~>2.3.0'
gem 'fluent-plugin-detect-exceptions', '~>0.0.11'
gem 'fluent-plugin-elasticsearch', '~>3.0.1'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.4.0'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'
gem 'fluent-plugin-systemd', '~>1.0.1'
gem 'fluent-plugin-rewrite-tag-filter', '~>2.2.0'
gem 'fluent-plugin-record-modifier', '~>2.0.1'
gem 'oj', '~>3.7.6'
